---
title: "La Liga Fichajes"
author: "Eric Morris"
date: "7/11/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(viridis)
library(readxl)
library(ggrepel)
require(scales)
library(ggimage)

knitr::opts_chunk$set(
  fig.align = "center",
  dpi = 300
)

```

## La Liga Fichajes Data Import

```{r}
fichajes = 
  read_excel("./data/1819_laliga_fichajes.xlsx", col_names = TRUE) %>% 
  janitor::clean_names() %>% 
  mutate(xg = as.numeric(x_g),
         xa = as.numeric(x_a),
         xg90 = as.numeric(x_g90),
         xa90 = as.numeric(x_a90)) %>% 
  mutate(xg90_plus_xa90 = xg90 + xa90,
         xg_plus_xa = xg + xa) %>% 
   select(-x_g, -x_a, -x_g90, -x_a90) 

club_badges_fichajes = 
  read_excel("./data/1819_laliga_logos.xlsx", col_names = TRUE) %>% 
  left_join(fichajes, by = c("club" = "club"))

fichajes_nogk =
  fichajes %>% 
  filter(g != "-")

club_badges_fichajes_nogk =
  club_badges_fichajes %>% 
  filter(g != "-")

team_fichajes = 
  fichajes_nogk %>% 
  group_by(club) %>% 
  summarize(sum_price = sum(price),
            sum_xg = sum(xg),
            sum_xa = sum(xa),
            sum_mp = sum(mp),
            n = n(),
            avg = sum(price)/n,
            ppxg = avg/sum(xg),
            ppmp = avg/sum(mp))

team_fichajes_badges =
  read_excel("./data/1819_laliga_logos.xlsx", col_names = TRUE) %>% 
  left_join(team_fichajes, by = c("club" = "club"))
  
```

## By team frugality and quantiles

```{r}
fichajes_nogk %>% 
  group_by(club) %>% 
  summarize(sum(price),
            sum(xg),
            sum(xa),
            sum(mp),
            n = n(),
            avg = sum(price)/n,
            ppxg = avg/sum(xg),
            ppmp = avg/sum(mp))

#Tiers for player labels

quantile(fichajes_nogk$xg_plus_xa, c(0.5, 0.75, 0.80, 0.85, 0.90, 0.95))

quantile(fichajes_nogk$price, c(0.5, 0.75, 0.80, 0.85, 0.90, 0.95))

quantile(fichajes_nogk$mp, c(0.5, 0.75, 0.80, 0.85, 0.90, 0.95))

quantile(fichajes$price, c(0.5, 0.75, 0.80, 0.85, 0.90, 0.95))

quantile(fichajes$mp, c(0.5, 0.75, 0.80, 0.85, 0.90, 0.95))

quantile(team_fichajes$sum_price, c(0.5, 0.75, 0.80, 0.85, 0.90, 0.95))

quantile(team_fichajes$sum_mp, c(0.5, 0.75, 0.80, 0.85, 0.90, 0.95))
```

## Charts 

```{r}

# Team chart (total minutes x total cost)

team_fichajes %>% 
  ggplot(aes(x = sum_price, y = sum_mp, color = club, size = n)) +
  geom_point(alpha = 0.75) + 
  geom_text_repel(aes(label = club, angle = 30, size = 2)) + 
  scale_color_manual(values = c("Athletic" = "red2",
                                "Alaves" = "blue",
                                "Atletico" = "red",
                                "Barcelona" = "maroon",
                                "Celta Vigo" = "lightblue",
                                "Eibar" = "dodgerblue4",
                                "Espanyol" = "mediumblue",
                                "Getafe" = "royalblue2",
                                "Girona" = "firebrick1",
                                "Leganes" = "dodgerblue",
                                "Levante" = "red4",
                                "Rayo Vallecano" = "gold",
                                "Real Betis" = "green3",
                                "Real Madrid" = "purple1",
                                "Real Sociedad" = "royalblue3",
                                "Real Valladolid" = "mediumpurple",
                                "Huesca" = "midnightblue",
                                "Sevilla" = "firebrick3",
                                "Valencia"  = "gray0",
                                "Villarreal" = "yellow3")) + 
  scale_x_continuous(breaks = seq(0, 145000000, 10000000)) + 
  scale_y_continuous(breaks = seq(1000, 14000, 500)) + 
  theme_bw() +
  theme(legend.position = "none")

# Player Chart (total min x total cost)

fichajes %>% 
  ggplot(aes(x = price, y = mp, color = club)) +
  geom_point(alpha = 0.75) + 
  geom_text_repel(aes(label = ifelse(mp >= 2600, name, ifelse(price >= 5000000, name, ''))), angle = 0, size = 2) +
  scale_color_manual(values = c("Athletic" = "red2",
                                "Alaves" = "blue",
                                "Atletico" = "red",
                                "Barcelona" = "maroon",
                                "Celta Vigo" = "lightblue",
                                "Eibar" = "dodgerblue4",
                                "Espanyol" = "mediumblue",
                                "Getafe" = "royalblue2",
                                "Girona" = "firebrick1",
                                "Leganes" = "dodgerblue",
                                "Levante" = "red4",
                                "Rayo Vallecano" = "gold",
                                "Real Betis" = "green3",
                                "Real Madrid" = "purple1",
                                "Real Sociedad" = "royalblue3",
                                "Real Valladolid" = "mediumpurple",
                                "Huesca" = "midnightblue",
                                "Sevilla" = "firebrick3",
                                "Valencia"  = "gray0",
                                "Villarreal" = "yellow3")) + 
    labs(title = "La Liga 2018 Incoming Transfers", 
       y = "Total League Minutes Played", 
       x = "Price (€)", 
       color = "Player's Team",
       caption = "Data: transfermarkt.com & understat.com 
       Graph: @ericdavidmorris") +
  scale_x_continuous(labels = comma, breaks = seq(0, 75000000, 5000000)) + 
  scale_y_continuous(breaks = seq(0, 4000, 500)) + 
  theme_bw() +
  theme(legend.position = "none") +
  theme(plot.title = element_text(hjust = 0.5))

fichajes_nogk %>% 
  ggplot(aes(x = price, y = xg_plus_xa, color = club)) +
  geom_point(alpha = 0.75) +
  geom_text_repel(aes(label = ifelse(xg_plus_xa >= 6.7, name, ifelse(price >= 23000000, name, ''))), angle = 30, size = 2) +
  scale_color_manual(values = c("Athletic Club" = "red2",
                                "Alaves" = "blue",
                                "Atletico Madrid" = "red",
                                "Barcelona" = "maroon",
                                "Celta Vigo" = "lightblue",
                                "Eibar" = "dodgerblue4",
                                "Espanyol" = "mediumblue",
                                "Getafe" = "royalblue2",
                                "Girona" = "firebrick1",
                                "Leganes" = "dodgerblue",
                                "Levante" = "red4",
                                "Rayo Vallecano" = "gold",
                                "Real Betis" = "green3",
                                "Real Madrid" = "purple1",
                                "Real Sociedad" = "royalblue3",
                                "Real Valladolid" = "mediumpurple",
                                "SD Huesca" = "midnightblue",
                                "Sevilla" = "firebrick3",
                                "Valencia"  = "gray0",
                                "Villarreal" = "yellow3")) + 
  labs(title = "La Liga Primera Vuelta - Offensive Value", 
       y = "Players NPxG / Team Total NPxG (%)", 
       x = "Non-Penalty Expected Goals plus Expected Assists per 90", 
       color = "Player's Team",
       caption = "Data: understat.com Graph: @ericdavidmorris
       Marked players are in top 10% of either category, min. 500 minutes played
       Dashed line represents 50th percentile") + 
  #scale_x_continuous(breaks = seq(0, 1.25, 0.05)) + 
  #scale_y_continuous(breaks = seq(0, 34, 1)) + 
  #geom_hline(yintercept = 3.95, linetype = "dashed", color = "black") + 
  #geom_vline(xintercept = 0.17, linetype = "dashed", color = "black") +
  theme_bw() +
  theme(legend.position = "bottom")
```

```{r}
##Charts with images

team_fichajes_badges %>% 
  ggplot(aes(x = sum_price, y = sum_mp)) +
  geom_image(aes(image = url), size = 0.04) +
  labs(title = "La Liga 2018 Summer Spending",
       y = "Total League MP by New Signings",
       x = "Total Sum Paid (€)",
       caption = "Data: transfermarkt.com & understat.com 
       Graph: @ericdavidmorris") +
  scale_x_continuous(labels = comma, breaks = seq(0, 145000000, 10000000)) + 
  scale_y_continuous(breaks = seq(0, 15500, 500)) + 
  theme_bw() +
  #geom_hline(yintercept = 6744, linetype = "dashed", color = "black") + 
  #geom_vline(xintercept = 24000000, linetype = "dashed", color = "black") +
  theme(plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(angle = 45, hjust = 1)) + 
  expand_limits(y = 0)


club_badges_fichajes %>% 
  ggplot(aes(x = price, y = mp)) +
  geom_image(aes(image = url), size = 0.01) + 
  geom_text_repel(aes(label = ifelse(mp >= 2600, name, ifelse(price >= 5000000, name, ''))), angle = 0, size = 2) +
  labs(title = "La Liga 2018 Incoming Transfers", 
       y = "Total League Minutes Played", 
       x = "Price (€)",
       caption = "Data: transfermarkt.com & understat.com 
       Graph: @ericdavidmorris") +
  scale_x_continuous(labels = comma, breaks = seq(0, 75000000, 5000000)) + 
  scale_y_continuous(breaks = seq(0, 4000, 500)) + 
  theme_bw() +
  theme(legend.position = "none") +
  theme(plot.title = element_text(hjust = 0.5))

```

