---
title: "KP Data"
author: "Eric Morris"
date: "3/19/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(viridis)
library(readxl)
library(ggrepel)
library(ggthemes)
```

## Import

```{r}
kp = 
  read_excel("./data/kp_tourney_stats.xlsx", col_names = TRUE) %>% 
  janitor::clean_names() %>% 
  mutate(eff_margin = adj_o - adj_d,
         year = as.character(year))

kp_s16 =
  read_excel("./data/kp_tourney_stats_s16.xlsx", col_names = TRUE) %>% 
  janitor::clean_names() %>% 
  mutate(eff_margin = adj_o - adj_d,
         year = as.character(year))
```


##Plot

```{r}
kp_f4 =
  kp %>% 
  filter(year %in% c("2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011",
                     "2012", "2013", "2014", "2015", "2016", "2017", "2018"))

quantile(kp_f4$adj_o, c(0.5, 0.75, 0.80, 0.85, 0.90, 0.95))

quantile(kp_f4$adj_d, c(0.5, 0.75, 0.80, 0.85, 0.90, 0.95))

kp %>% 
  ggplot(aes(x = adj_d, y = adj_o, color = ifelse(champion == 1, "gold", ifelse(year == "2019", "red", "black")))) +
  geom_point(alpha = 0.5, size = 3) +
  geom_text_repel(aes(label = ifelse(champion == 1, paste(team, year, sep = ' '), ifelse(champ_game == 1, paste(team, year, sep = ' '), ifelse(year == 2019, team, '')))), angle = 15, size = 2) +
  #geom_text_repel(aes(label = ifelse(champion == 1, year, ifelse(champ_game == 1, year, ifelse(year == 2019, year, '')))), angle = 0, size = 3) +
  labs(title = "KP AdjO vs. AdjD - NCAA Final Four Teams since 2002 and 2019 KP Top 25", 
       y = "AdjO", 
       x = "AdjD",
       caption = "Data: kenpom.com 
       Graph: @ericdavidmorris
       Labeled: Won NCAA championship, were in NCAA Final, or is a current 2019 team
       Dashed Lines represent Median Final Four AdjO (117.95) and AdjD (90.95)") + 
  scale_colour_manual(values = c("black", "blue", "red"),
                      name = "Colors",
                      breaks = c("black", "blue", "red"),
                      labels = c("Final Four Team", "Won Championship", "2019 Team")) +
  scale_x_continuous(breaks = seq(84, 100, 0.5)) + 
  scale_y_continuous(breaks = seq(106, 130, 1)) + 
  geom_hline(yintercept = 117.95, linetype = "dashed", color = "black", alpha = 0.5) + 
  geom_vline(xintercept = 90.95, linetype = "dashed", color = "black", alpha = 0.5) +
  theme_classic() +
  theme(legend.position = "bottom")

kp_s16 %>% 
  ggplot(aes(x = adj_d, y = adj_o, color = ifelse(champion == 1, "gold", ifelse(year == "2019", "red", "black")))) +
  geom_point(alpha = 0.75, size = 3) +
  geom_text_repel(aes(label = ifelse(champion == 1, paste(team, year, sep = ' '), ifelse(champ_game == 1, paste(team, year, sep = ' '), ifelse(year == 2019, team, '')))), size = 2.5) +
  #geom_text_repel(aes(label = ifelse(champion == 1, year, ifelse(champ_game == 1, year, ifelse(year == 2019, year, '')))), angle = 0, size = 3) +
  labs(title = "KP AdjO vs. AdjD - NCAA Final Four Teams since 2002 and 2019's Sweet Sixteen", 
       y = "AdjO", 
       x = "AdjD",
       caption = "Data: kenpom.com 
       Graph: @ericdavidmorris
       Labeled: Won NCAA championship, were in NCAA Final, or is a current 2019 S16 team
       Dashed Lines represent Median Final Four AdjO (117.95) and AdjD (90.95)") + 
  scale_colour_manual(values = c("black", "blue", "red"),
                      name = "Colors",
                      breaks = c("black", "blue", "red"),
                      labels = c("Final Four Team", "Won Championship", "2019 S16")) +
  scale_x_reverse() + 
  #scale_x_continuous(breaks = seq(84, 100, 0.5)) + 
  scale_y_continuous(breaks = seq(106, 130, 1), position = "right") + 
  geom_hline(yintercept = 117.95, linetype = "dashed", color = "black", alpha = 0.5) + 
  geom_vline(xintercept = 90.95, linetype = "dashed", color = "black", alpha = 0.5) +
  theme_classic() +
  theme(legend.position = "bottom")
```

