---
title: "NBA Total MP"
author: "Eric Morris"
date: "3/11/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(viridis)
library(readxl)
library(ggrepel)

knitr::opts_chunk$set(
  fig.align = "center",
  dpi = 800
)
```

## MP Data from Basketball Reference

All data was pulled from [Basketball Reference](https://www.basketball-reference.com/) on March 11, 2019. Included is total minutes played for the [regular season](https://www.basketball-reference.com/leaders/mp_career.html) and the [playoffs](https://www.basketball-reference.com/leaders/mp_career_p.html) since the 1951-1952 season. Only the top 200 in both regular season and playoff total minutes were pulled. 

```{r Import}
reg_total_mp = 
  read_excel("./data/total_reg_mp_3_11_all_stats.xlsx", col_names = TRUE) %>% 
  janitor::clean_names() %>% 
  separate(player, into = c("player", "trash"), sep = "\\\\") %>% 
  mutate(reg_total_mp = mp,
         seasons = (to - from) + 1,
         active = ifelse(to == 2019, 1, 0)) %>% 
  select(-rk, -trash)

playoff_total_mp = 
  read_excel("./data/playoff_total_3_11_all_stats.xlsx", col_names = TRUE) %>% 
  janitor::clean_names() %>% 
  separate(player, into = c("player", "trash"), sep = "\\\\") %>% 
  mutate(playoff_total_mp = mp) %>% 
  select(-rk, -trash)

reg_playoff_merge = 
  inner_join(reg_total_mp, playoff_total_mp, by = "player") %>% 
  select(-ends_with(".x"), -ends_with(".y")) %>% 
  mutate(total_mp = (reg_total_mp + playoff_total_mp))

#write.csv(reg_playoff_merge,'merged.csv')
```

## First Chart

```{r chart}
quantile(reg_playoff_merge$total_mp, c(0.5, 0.75, 0.80, 0.85, 0.90, 0.95))

quantile(reg_playoff_merge$seasons, c(0.5, 0.75, 0.80, 0.85, 0.90, 0.95))

reg_playoff_merge %>% 
  ggplot(aes(x = seasons, y = total_mp, color = active)) +
  geom_point(alpha = 0.75, size = 3) +
  geom_text_repel(aes(label = ifelse(seasons >= 19, player, ifelse(total_mp >= 52630, player, ifelse(active == 1, player, '')))), angle = 0, size = 3) +
  labs(title = "NBA Minutes Played Leaders Since 1951-1952", 
       y = "Total Minutes Played (Regular Season + Playoffs)", 
       x = "Seasons Played",
       caption = "Data: Basketball Reference Graph: @ericdavidmorris
       Marked players are in top 10% of either axis
       Blue players are still active") + 
  scale_x_continuous(breaks = seq(10, 22, 1)) + 
  scale_y_continuous(breaks = seq(30000, 68000, 2000)) + 
  theme_bw() +
  theme(legend.position = "none")

reg_playoff_merge %>% 
  arrange(desc(total_mp)) %>% 
  top_n(20) %>% 
  rename("Player" = player,
         "Regular Season Total MP" = reg_total_mp,
         "Seasons Played" = seasons,
         "Playoff Total MP" = playoff_total_mp,
         "Total Minutes" = total_mp) %>% 
  knitr::kable(align = "c")
```

## New Year by Year Data, Top 11

```{r}
mpyby = 
  read_excel("./data/yearbyyearMPtop11.xlsx", col_names = TRUE) %>% 
  janitor::clean_names() %>% 
  mutate(total_year_mp = reg_total_min + playoff_total_min) 

mpyby_sum =
  mpyby %>% 
  group_by(player) %>% 
  mutate(cumsum_min = cumsum(total_year_mp))

mpyby %>% 
  ggplot(aes(x = career_season_number, y = total_year_mp)) +
  geom_line(aes(color = player), alpha = 0.75, size = 3) +
 # geom_text_repel(aes(label = player, angle = 0, size = 3)) +
  labs(title = "Top 11 in Total NBA Minutes Played", 
       y = "Total Minutes Played (Regular Season + Playoffs)", 
       x = "Seasons Played",
       caption = "Data: Basketball Reference Graph: @ericdavidmorris") + 
  scale_x_continuous(breaks = seq(0, 22, 1)) + 
  #scale_y_continuous(breaks = seq(30000, 68000, 2000)) + 
  theme_bw() +
  theme(legend.position = "none")

mpyby_sum %>% 
  ggplot(aes(x = career_season_number, y = cumsum_min)) +
  geom_line(aes(color = player), alpha = 0.75, size = 1) +
 # geom_text_repel(aes(label = player, angle = 0, size = 3)) +
  labs(title = "Top 11 in Total NBA Minutes Played", 
       y = "Total Minutes Played (Regular Season + Playoffs)", 
       x = "Seasons Played",
       caption = "Data: Basketball Reference 
       Plot: @ericdavidmorris") + 
  scale_x_continuous(breaks = seq(0, 22, 1)) + 
  #scale_y_continuous(breaks = seq(30000, 68000, 2000)) + 
  theme_bw() +
  theme(legend.position = "none")
```

# Top 20

```{r}
mpyby20 = 
  read_excel("./data/yearbyyearMPtop20.xlsx", col_names = TRUE) %>% 
  janitor::clean_names() %>% 
  mutate(total_year_mp = reg_total_min + playoff_total_min) 

mpyby20_sum =
  mpyby20 %>% 
  group_by(player) %>% 
  mutate(cumsum_min = cumsum(total_year_mp))

mpyby20_sum %>% 
  group_by(player) %>% 
  summarise(max(cumsum_min))

mpyby20_sum %>% 
  group_by(player) %>% 
  ggplot(aes(x = career_season_number, y = cumsum_min)) +
  geom_line(aes(color = player), alpha = 0.5, size = 1) +
  geom_point(aes(color = player), alpha = 0.5) + 
  #geom_text_repel(aes(label = ifelse(ring == 1, "*", ''), angle = 0, size = 1, color = player)) +
  geom_text_repel(aes(label = ifelse(final_season == 1, player, ''), color = player, angle = 0, size = 0.5), no_overlap = TRUE, force = 10) +
  labs(title = "Top 20 in Total NBA Minutes Played All-Time", 
       y = "Total Minutes Played (Regular Season + Playoffs)", 
       x = "Seasons Played",
       color = "Player",
       caption = "Data: Basketball Reference 
       Plot: @ericdavidmorris") + 
  scale_x_continuous(breaks = seq(1, 22, 1)) + 
  scale_y_continuous(breaks = seq(0, 68000, 2000)) + 
  #scale_color_viridis(discrete = TRUE) + 
  theme_bw() +
  theme(legend.position = "bottom")

```

